version: '3.8'
services:
  server:
    image: nginx
    ports:
      - 8000:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./src:/var/www/html:delegated
    depends_on:
      - php
      - mysql
      - phpmyadmin
  php:
    build:
      context: ./dockerfiles
      dockerfile: php.dockerfile
    volumes:
      # delegated : (used for Optimisation) : if the container write file , dont write them immedatly on the host 
      - ./src:/var/www/html:delegated
  mysql:
    image: mysql
    env_file:
      - .env/mysql.env
  phpmyadmin:
    image: phpmyadmin
    env_file:
      - .env/mysql.env
    environment:
      - PMA_HOST=mysql
    ports:
      - 8080:80
    depends_on:
      - mysql
  composer:
    build:
      context: ./dockerfiles
      dockerfile: composer.dockerfile
    volumes:
      - ./src:/var/www/html
  artisan:
    build:
      context: ./dockerfiles
      dockerfile: php.dockerfile
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    entrypoint: [ "php", "artisan" ]
  npm:
    image: node:16-alpine
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    entrypoint: [ "npm" ]
